//! TypeScript IPC contract export (run via `cargo test export_typescript_bindings`).

#[cfg(test)]
mod tests {
    use std::path::Path;

    #[test]
    fn export_typescript_bindings() {
        let output =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/types/generated/bindings.ts");
        if let Some(parent) = output.parent() {
            std::fs::create_dir_all(parent).expect("create generated types dir");
        }

        let contents = r"// Auto-generated by `cargo test export_typescript_bindings`. Do not edit.

/** Mirrors Rust `IpcErrorPayload` / `PakerError` over IPC. */
export interface IpcErrorPayload {
  code: string;
  message: string;
  userAction?: string;
}

/** Mirrors Rust `UpdateInfo` from `check_for_update`. */
export interface UpdateInfoGenerated {
  currentVersion: string;
  latestVersion: string;
  updateAvailable: boolean;
  releaseUrl: string;
  releaseName: string;
}

/** Mirrors Rust `ConnectionProfile` / frontend `S3Connection` (no secrets). */
export interface ConnectionProfileGenerated {
  id: string;
  name: string;
  endpoint?: string;
  region: string;
  accessKeyId: string;
  forcePathStyle: boolean;
  skipTlsVerify: boolean;
  defaultBucket?: string;
}
";
        std::fs::write(&output, contents).expect("write bindings.ts");
    }
}
